# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchCod', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=100)),
                ('branchDefault', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], max_length=1)),
                ('branchLastCommit', models.CharField(max_length=300)),
            ],
        ),
    ]
